/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'asig' at '23/09/15 13:33' with Gradle 2.6
 *
 * @author asig, @date 23/09/15 13:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
